name: Deploy to Amazon AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: Dependency Installation
        run: npm install

      - name: Build Application
        run: npm run build

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:
          aws-secret-access-key:

        
        
      
    
      
      

